### ISSUE TITLE
App appears to hang after generating the files with Node 10.12.0

### ISSUE THREAD

**Issue by andrewlock** [probot/create-probot-app#49]
Just thought I'd give the app a try, but it appears to hang creating the files. I've tried with two different templates (`basic-js`, `basic-ts`), from powershell and cmd window, and I've tried passing in the template using the `--template` parameter. In all cases, it never writes `created files...`, and seems to hang indefinitely. It never runs an `npm install` as far as I can tell.

I'm on Windows 10 1803, and using Node 10.12.0.

I tried again by switching to Node 8.11.4  (I'm using NVM for Windows) and the app installed fine (though it failed to install, as it didn't `cd` into the new directory first as far as I can tell

Thanks!

**Comment by RandellDawson** [comment]
I have been trying to get `npx create-probot-app` working for about 3 days solid now.  I am on Windows 8.1 and finally figured out that you must have Python 2.7 (not 3+) and do not used Node 10+, because it will not work (the hang you mention).  I create a new directory first and just run `npx create-probot-app` inside the new directory.  I ran all of this on PowerShell because Git Bash was not working well either.  

It would attempt to install, but then error with the following:
```
> node-gyp rebuild || node suppress-error.js


D:\Coding\probot2\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio
 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Coding\probot2\node_modules\dtrace-provider\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Coding\probot2\node_modules\dtrace-provider
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> nodemon@1.18.9 postinstall D:\Coding\probot2\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 955 packages from 542 contributors in 89.648s

Done! Enjoy building your Probot app!
```
Then, when I look in the main folder, there are all these extra files, which I think should not be there.
```
    Directory: D:\Coding\probot-two


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         1/14/2019  10:19 AM            node_modules
d----         1/14/2019  10:17 AM            test
-a---         1/14/2019  10:17 AM        236 .env.example
-a---         1/14/2019  10:19 AM        321 acorn
-a---         1/14/2019  10:19 AM        198 acorn.cmd
-a---         1/14/2019  10:17 AM       4672 app.yml
-a---         1/14/2019  10:19 AM        323 atob
-a---         1/14/2019  10:19 AM        200 atob.cmd
-a---         1/14/2019  10:19 AM        335 babylon
-a---         1/14/2019  10:19 AM        212 babylon.cmd
-a---         1/14/2019  10:19 AM        325 bunyan
-a---         1/14/2019  10:19 AM        202 bunyan.cmd
-a---         1/14/2019  10:17 AM       3232 CODE_OF_CONDUCT.md
-a---         1/14/2019  10:17 AM       2198 CONTRIBUTING.md
-a---         1/14/2019  10:19 AM        343 escodegen
-a---         1/14/2019  10:19 AM        220 escodegen.cmd
-a---         1/14/2019  10:19 AM        345 esgenerate
-a---         1/14/2019  10:19 AM        222 esgenerate.cmd
-a---         1/14/2019  10:19 AM        331 eslint
-a---         1/14/2019  10:19 AM        208 eslint.cmd
-a---         1/14/2019  10:19 AM        335 esparse
-a---         1/14/2019  10:19 AM        212 esparse.cmd
-a---         1/14/2019  10:19 AM        341 esvalidate
-a---         1/14/2019  10:19 AM        218 esvalidate.cmd
-a---         1/14/2019  10:19 AM        341 handlebars
-a---         1/14/2019  10:19 AM        218 handlebars.cmd
-a---         1/14/2019  10:19 AM        347 import-local-fixture
-a---         1/14/2019  10:19 AM        224 import-local-fixture.cmd
-a---         1/14/2019  10:17 AM        461 index.js
-a---         1/14/2019  10:19 AM        315 is-ci
-a---         1/14/2019  10:19 AM        192 is-ci.cmd
-a---         1/14/2019  10:19 AM        323 jest
-a---         1/14/2019  10:19 AM        355 jest-runtime
-a---         1/14/2019  10:19 AM        232 jest-runtime.cmd
-a---         1/14/2019  10:19 AM        200 jest.cmd
-a---         1/14/2019  10:19 AM        335 js-yaml
-a---         1/14/2019  10:19 AM        212 js-yaml.cmd
-a---         1/14/2019  10:19 AM        321 jsesc
-a---         1/14/2019  10:19 AM        198 jsesc.cmd
-a---         1/14/2019  10:19 AM        323 json5
-a---         1/14/2019  10:19 AM        200 json5.cmd
-a---         1/14/2019  10:17 AM        772 LICENSE
-a---         1/14/2019  10:19 AM        329 loose-envify
-a---         1/14/2019  10:19 AM        206 loose-envify.cmd
-a---         1/14/2019  10:19 AM        313 mime
-a---         1/14/2019  10:19 AM        190 mime.cmd
-a---         1/14/2019  10:19 AM        325 mkdirp
-a---         1/14/2019  10:19 AM        202 mkdirp.cmd
-a---         1/14/2019  10:19 AM        313 ncp
-a---         1/14/2019  10:19 AM        190 ncp.cmd
-a---         1/14/2019  10:19 AM        335 nodemon
-a---         1/14/2019  10:19 AM        212 nodemon.cmd
-a---         1/14/2019  10:19 AM        335 nodetouch
-a---         1/14/2019  10:19 AM        212 nodetouch.cmd
-a---         1/14/2019  10:19 AM        323 nopt
-a---         1/14/2019  10:19 AM        200 nopt.cmd
-a---         1/14/2019  10:17 AM       1034 package.json
-a---         1/14/2019  10:19 AM        331 probot
-a---         1/14/2019  10:19 AM        208 probot.cmd
-a---         1/14/2019  10:19 AM        321 raven
-a---         1/14/2019  10:19 AM        198 raven.cmd
-a---         1/14/2019  10:19 AM        309 rc
-a---         1/14/2019  10:19 AM        186 rc.cmd
-a---         1/14/2019  10:17 AM        480 README.md
-a---         1/14/2019  10:19 AM        317 rimraf
-a---         1/14/2019  10:19 AM        194 rimraf.cmd
-a---         1/14/2019  10:19 AM        321 sane
-a---         1/14/2019  10:19 AM        198 sane.cmd
-a---         1/14/2019  10:19 AM        325 semver
-a---         1/14/2019  10:19 AM        202 semver.cmd
-a---         1/14/2019  10:19 AM        323 shjs
-a---         1/14/2019  10:19 AM        200 shjs.cmd
-a---         1/14/2019  10:19 AM        337 smee
-a---         1/14/2019  10:19 AM        214 smee.cmd
-a---         1/14/2019  10:19 AM        331 sshpk-conv
-a---         1/14/2019  10:19 AM        208 sshpk-conv.cmd
-a---         1/14/2019  10:19 AM        331 sshpk-sign
-a---         1/14/2019  10:19 AM        208 sshpk-sign.cmd
-a---         1/14/2019  10:19 AM        335 sshpk-verify
-a---         1/14/2019  10:19 AM        212 sshpk-verify.cmd
-a---         1/14/2019  10:19 AM        329 standard
-a---         1/14/2019  10:19 AM        206 standard.cmd
-a---         1/14/2019  10:17 AM         81 travis.yml
-a---         1/14/2019  10:19 AM        335 uglifyjs
-a---         1/14/2019  10:19 AM        212 uglifyjs.cmd
-a---         1/14/2019  10:19 AM        317 uuid
-a---         1/14/2019  10:19 AM        194 uuid.cmd
-a---         1/14/2019  10:19 AM        315 watch
-a---         1/14/2019  10:19 AM        192 watch.cmd
-a---         1/14/2019  10:19 AM        321 which
-a---         1/14/2019  10:19 AM        198 which.cmd
```
After some further research, I found I had to run `npm install --global --production windows-build-tools` and then use the same sequence I mention above and it would complete without the above error, but would still show:
```
> dtrace-provider@0.8.7 install D:\Coding\probot-two\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


D:\Coding\probot-two\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node
_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

> nodemon@1.18.9 postinstall D:\Coding\probot-two\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

added 955 packages from 542 contributors in 74.122s

Done! Enjoy building your Probot app!
```
and all those extra files would still be in the directory.  I posted on the slack channel about this and @tcbyrd asked me to report it over here.  Since you already posted this here, I decided to just add my results here.  If the mods want me to create a separate issue, I will, but I feel this is all related to trying to install using Windows.

**Comment by andrewlock** [comment]
This is still relevant, it's a poor experience using on Windows.
