### ISSUE TITLE
What causes DEBUG github: GitHub request: GET /app/installations - 401 undefined (installation=undefined)?

### ISSUE THREAD

**Issue by RandellDawson** [probot/create-probot-app#50]
When using `npm run dev` or `npm start` I get the following.  What are the typical reasons why I would get this?
```
$ npm run dev

> @freecodecamp/contribute@1.0.0 dev D:\Coding\github-tools\probot
> nodemon

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .env *.*
[nodemon] starting `npm start`

> @freecodecamp/contribute@1.0.0 start D:\Coding\github-tools\probot
> probot run ./index.js

03:05:03.413Z  INFO probot: Forwarding https://smee.io/E5PuAGGdkbjemQ6 to http://localhost:3001/
03:05:03.418Z  INFO probot: Listening on http://localhost:3001
03:05:03.719Z DEBUG github: GitHub request: GET /app/installations - 401 undefined (installation=undefined)
  params: {
    "per_page": 100,
    "baseUrl": "https://api.github.com",
    "request": {
      "timeout": 0
    }
  }
03:05:03.723Z ERROR probot: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documenta
tion_url":"https://developer.github.com/v3"}
  HttpError: {"message":"'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires","documentation_url":"http
s://developer.github.com/v3"}
      at response.text.then.message (D:\Coding\github-tools\probot\node_modules\@octokit\rest\lib\request\request.js:72:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
03:05:03.830Z  INFO probot: Connected https://smee.io/E5PuAGGdkbjemQ6
```
It works fine on someone else' machine (Mac).  Is this a Windows specific issue?

**Comment by ogmag** [comment]
Great
